### ISSUE TITLE
RFC: rust development when some dependency is compiled with asan enabled

### ISSUE THREAD

**Issue by leoadonia** [TEN-framework/ten_framework.bak#14]
1. 背景
  
   ten_framework 中会存在 C 和 Rust 依赖的问题，依赖关系如下:

   * `ten_rust` (Rust project) 会依赖 `ten_utils` (C project) 的静态库.
   * `ten_runtime` (C project) 会依赖 `ten_rust` (Rust project) 输出的 静态库.

   ten_utils 和 ten_runtime 是通过 TGN 工具链编译的, 通过 --enable_sanitizer 参数控制是否开启 asan. 同时, 对 libasan-rt 的依赖是 clang 或者 gcc 提供的.

   而 ten_rust 和 ten_manager 作为 Rust 工程，触发编译的场景有两个:

   * 通过 TGN 中的 tamplate, 包装了 cargo build 命令, 由 TGN 触发编译. 这种情况下，会统一根据 TGN 中的 --enable_sanitizer 参数来判断是否开启 RUST 的 asan. 如果开启，在 cargo build 的环境变量中添加需要的 RUSTFLAGS.  --- 不影响
   * 在 vscode 开发，通过 vscode 中的 Run 按钮触发编译; 或者在命令行执行 cargo 相关的命令，如 cargo build, cargo test, cargo check 等. --- 会有影响，无法链接 asan 相关的 symbol. 因为 vscode 中的 Run 按钮是 vscode 的 task，不是 rust-analyzer 提供的功能.
   * 在 vscode 中，通过 launch.json 开启 debug 任务，可以设置 env 参数. --- 不影响

   在 Rust 中开启 ASAN 的方式有如下三种:

   * 通过环境变量，RUSTFLAGS=-Zsanitizer=address.
      > 需要注意的是，该环境变量是作用于 cargo 的，不是 rustc. cargo 会根据该环境变量，设置 rustc 执行的 flag -- `-Z sanitizer=address`. 也就是说，在 build.rs 中通过如 `env::set_var` 的方式设置环境变量并不会生效.
   * 通过在 .cargo/config.toml 中设置 rustflags. 如:
      ```toml
      [target.x86_64-unknown-linux-gnu]
      rustflags = ["-Z", "sanitizer=address"]
      ```
      > 同样, 也不能在 build.rs 中，通过如 `println!("cargo::rustc-flags=-Zsanitizer=address") 的方式设置. 因为在 build.rs 中，cargo 只允许设置 -L, -l 等，不允许 -Z 参数.

    * 在 build.rs 中通过设置 linker, 如 `println!("cargo::rustc-link-lib=asan"`). 但这种方式，会有如下问题:
        * rustc-link-lib 是作用于 rustc 的 ld 的, 意味着如果不指定 `rustc-link-search` 的话，找到的是系统下的 asan，而不是 rustc toolchain 下的 asan (一般在 ~/.rustup/toolchains/<target_cpu>/lib/rustlib/<target_cpu>/lib/librustc-nightly_rt.asan.a). 相当于是依赖外部的 libasan-rt, 对于 rust 来说，需要搭配 `rustflags = ["-Z", "external-clangrt"]` 使用.
        * 同时, 对于 crate-type 是 bin 的 crate 来说, 就是动态依赖 asan，需要在执行时，通过 LD_PRELOAD 优先加载 asan.
        * 另外，这种方式是指定 libasan-rt 的源，而不是在决定是否 `开启` asan.

   同时，在 build.rs 中，通过如下方式设置均不生效:
   * env::set_var("RUSTFLAGS", "-Zsanitizer=address") 
   * println!("cargo:rustc-env=RUSTFLAGS=-Zsanitizer=address")
   * println!("cargo:rustc-flags=-Zsanitizer=address")

   build.rs 的作用是 cargo 会将 build.rs 中的输出(即 `println!` ) 保存到 target/deps/<crate>/build/output 文件中, 作为 rustc 编译器的参数设置. 所以, 在 build.rs 中设置环境变量, 并不会作用到 rustc 的执行链中.

  cargo 中查找 `RUSTFLAGS` 的顺序(参考 [cargo 源码](https://github.com/rust-lang/cargo/blob/master/src/cargo/core/compiler/build_context/target_info.rs#L701)):

   * 先找 `CARGO_ENCODED_RUSTFLAGS` 和 `RUSTFLAGS` 系统环境变量.
   * 如果环境变量不存在，则从 .cargo/config.toml 中查找. 查找的优先级顺序为:
       * `target.\*.rustflags`
       * `target.cfg(..).rustflags`
       * `host.\*.rustflags`, 但依赖开启 `-Zhost-config`.
       * `build.rustflags`

在开启 asan 时，执行 cargo 相关的命令，必须加上  `--target` 命令，或者执行命令时，带上 `-Zhost-config` 参数.
 
2. 预期达到的目标
    在使用 TGN 编译 ten_utils, 并且开启 ASAN 时，依赖 ten_utils 的 ten_rust 和 ten_manager 可以同时满足以下开发场景:

    * 通过 vscode 中的 Run/Debug Test 按钮，可以正常运行和调试用例.
    * 在命令行，通过 cargo build 或 cargo build --tests，可以正常编译.
    * 在命令行，通过 cargo test, 可以执行测试用例.
    * 在命令行，通过 tgn build ... 可以正常执行编译.
   
3. 实现方式

     如上所述, 在 vscode 中开发时，影响因素有两个:
     * 需要通知 cargo 开启 asan
     * 需要不指定 `--target` 参数，或者说, 指定默认的 target 参数.

     基于此，最佳的实现方式是，在使用 TGN 编译 ten_utils 时，如果开启了 ASAN, 在 ten_framework 目录下生成 .cargo/config.toml, 内容如下:

      ```toml
      [target.x86_64-unknown-linux-gnu]
      rustflags = ["-Z", "sanitizer=address"]

      [build]
      target = "x86_64-unknown-linux-gnu"
      ```

      具体 target 的值，根据 os 和 cpu 判断.

      在下次编译，删除该配置.

       cargo 中 config.toml 的作用范围如下:

        假如在 /projects/foo/bar/baz 目录下执行编译，config.toml 的查找路径为:

        * /projects/foo/bar/baz/.cargo/config.toml
        * /projects/foo/bar/.cargo/config.toml
        * /projects/foo/.cargo/config.toml
        * /projects/.cargo/config.toml
        * /.cargo/config.toml
        * $CARGO_HOME/config.toml , 默认是:
              Windows: %USERPROFILE%\.cargo\config.toml
              Unix: $HOME/.cargo/config.toml

        所以，在 ten_framework/.cargo/config.toml 中设置，可以满足上述所有场景，同时对开发者无感知.

**Comment by leoadonia** [comment]
如果 ten_framework/.cargo/config.toml 存在，内容如下:

```toml
[target.x86_64-unknown-linux-gnu]
rustflags = ["-Z", "sanitizer=address"]


[build]
target = "x86_64-unknown-linux-gnu"
```

同时, ten_rust/.cargo/config.toml 存在，内容如下:

```toml
[target.x86_64-unknown-linux-gnu]
rustflags = ["-l", "ten_utils_static"]
```

测试结果显示，在编译 ten_rust 时，rustflags 是合并了，而不是 cargo 在找到当前 crate 下的 config.toml 中包含 rustflags 就不往上找了. 

> TODO: 确认 cargo 的逻辑.
